Update to version 3.2.8
Clarify what the cron entry is doing in the comment.
Change to a more verbose message when creating bash_history.archive.
Clarify what ed is doing in the cut and paste function on the comment.

diff --git a/HistLog b/HistLog
--- a/HistLog
+++ b/HistLog
@@ -4,9 +4,9 @@
 #: Title           : HistLog                                                                   #
 #: Sypnosis        : HistLog                                                                   #
 #: Date Created    : Sun Jul 27 18:07:40 PHT 2014 / Sun Jul 27 10:08:00 UTC 2014               #
-#: Last Edit       : Fri Feb  6 22:10:41 PHT 2015 / Fri Feb  6 14:10:41 UTC 2015               #
+#: Last Edit       : Sat Feb  7 09:28:18 PHT 2015 / Sat Feb  7 01:28:18 UTC 2015               #
 #: License         : GPLv3                                                                     #
-#: Version         : 3.2.7                                                                     #
+#: Version         : 3.2.8                                                                     #
 #: Author          : Jason V. Ferrer '<jetchisel@opensuse.org>'                                #
 #: Description     : Logs ~/.bash_history to ~/.bash_history.archive  after 10000 lines.       #
 #: Options         : NONE                                                                      #
@@ -103,7 +103,7 @@ export EDITOR
 
 # ******************************************************************************************** #
 #                                                                                              #
-#     Function to create an entry in cron (every 30 seconds) using ed and a heredoc.           #
+#    Function to create an entry in cron (to run every 30 seconds) using ed and a heredoc.     #
 #                                                                                              #
 # ******************************************************************************************** #
 
@@ -129,14 +129,26 @@ fi
 
 # ******************************************************************************************** #
 #                                                                                              #
-#   Define bash_history bash_history.archive log file. If Archive does not exists create it.   #
+#         Assign/define bash_history and bash_history.archive log file in a variable.          #
 #                                                                                              #
 # ******************************************************************************************** #
 
 History=${HOME}/.bash_history
 Archive=${HOME}/.bash_history.archive
 
-[[ -s $Archive ]] || > "$Archive"
+# ******************************************************************************************** #
+#                                                                                              #
+#      If bash_history.archive does not exists create it, otherwise exit with an error.        #
+#                                                                                              #
+# ******************************************************************************************** #
+
+if [[ ! -f $Archive ]]; then
+  printf '%s\n' "Creating ${Archive}..."
+  > "$Archive" || die "Could not create ${Archive}!"
+  printf '%s\n' "$Archive created succesfully."
+else
+  printf '%s\n' "$Archive exists."
+fi
 
 # ******************************************************************************************** #
 #                                                                                              #
@@ -159,7 +171,7 @@ PasteLines=5001,\$
 
 # ******************************************************************************************** #
 #                                                                                              #
-# Function to Cut 50001 down to the last from .bash_history and paste to .bash_history.archive.#
+# Function to Cut from 1 down 5000 lines from .bash_history and paste to .bash_history.archive.#
 #                                                                                              #
 # ******************************************************************************************** #
 
