Update to version 2.1.0 Add warn and die function Add check for the required app/executable. Create a variable that holds lines to cut/paste Rename SourcFile to History and add Archive Use the variable that holds line values inside ed

diff --git a/HistLog b/HistLog
--- a/HistLog
+++ b/HistLog
@@ -4,15 +4,35 @@
 #: Title           : HistLog                                                                   #
 #: Sypnosis        : HistLog                                                                   #
 #: Date Created    : Sun Jul 27 18:07:40 PHT 2014 / Sun Jul 27 10:08:00 UTC 2014               #
-#: Last Edit       : Wed Jan 28 12:50:18 PHT 2015 / Wed Jan 28 04:50:18 UTC 2015               #
+#: Last Edit       : Thu Jan 29 07:52:58 PHT 2015 / Wed Jan 28 23:52:58 UTC 2015               #
 #: License         : GPLv3                                                                     #
-#: Version         : 2.0.0                                                                     #
+#: Version         : 2.1.0                                                                     #
 #: Author          : Jason V. Ferrer '<jetchisel@opensuse.org>'                                #
 #: Description     : Logs ~/.bash_history to ~/.bash_history.archive  after 10000 lines.       #
 #: Options         : NONE                                                                      #
 #: Home Page       : NONE                                                                      #
 #: ExtComm         : ed,wc                                                                     #
 # ============================================================================================ #
+
+# *********************************************************************************************#
+#                                                                                              #
+#   Warn and die functions, for exit messages and default status or an optional exit status.   #
+#                                                                                              #
+# *********************************************************************************************#
+
+warn() {
+  printf '%s\n' "${BASH_SOURCE##*/}: error: $*" >&2
+}
+
+die() {
+  local st=$?
+  case $2 in
+    *[^0-9]*|'') :;;
+    *) st=$2;;
+  esac
+  warn "$1"
+  exit "$st"
+}
 
 # ******************************************************************************************** #
 #                                                                                              #
@@ -40,20 +60,32 @@ export PATH
 
 # ******************************************************************************************** #
 #                                                                                              #
-#                                  The dashes variable.                                        #
+#          Check for the required app/executable is with in your PATH, exit otherwise.         #
 #                                                                                              #
 # ******************************************************************************************** #
 
-Length=92
-printf -v Line '#%*s#' "$Length"
+Missing=()
+ExtComm=(ed wc)
+MissingMessage="is either not installed or it is not in your PATH!"
+ExitMessage="Please install the following: "
+
+for apps in "${ExtComm[@]}"; do
+  if ! type -P "$apps" >/dev/null; then
+    echo "$apps $MissingMessage" >&2
+    Missing+=("$apps")
+  fi
+done
+
+(( ! ${#Missing[@]} )) || die "$ExitMessage[${Missing[*]}] exiting now!"
 
 # ******************************************************************************************** #
 #                                                                                              #
-#                             Define bash_history log file.                                    #
+#                   Define bash_history bash_history.archive log file.                         #
 #                                                                                              #
 # ******************************************************************************************** #
 
-SourceFile=${HOME}/.bash_history
+History=${HOME}/.bash_history
+Archive=${HOME}/.bash_history.archive
 
 # ******************************************************************************************** #
 #                                                                                              #
@@ -61,22 +93,32 @@ SourceFile=${HOME}/.bash_history
 #                                                                                              #
 # ******************************************************************************************** #
 
-Total_Lines=$(wc -l < "$SourceFile")
+Total_Lines=$(wc -l < "$History")
+
 
 # ******************************************************************************************** #
 #                                                                                              #
-#        Function to Cut from .bash_history and paste to .bash_history.archive                 #
+#  lines to cut from history and lines to be pasted in archive. (Adjust the value if needed).  #
+#                                                                                              #
+# ******************************************************************************************** #
+
+CutLines=5001
+PasteLines=5000
+
+# ******************************************************************************************** #
+#                                                                                              #
+#  Function to Cut from .bash_history and paste to .bash_history.archive (leave 5,000 lines).  #
 #                                                                                              #
 # ******************************************************************************************** #
 
 CutAndPaste() {
-ed -s /home/jetchisel/.bash_history <<'EOF'
-5001,$d
+ed -s "$History" <<EOF
+$CutLines,\$d
 w
 u
-1,5000d
-.- r /home/jetchisel/.bash_history.archive
-w /home/jetchisel/.bash_history.archive
+1,${PasteLines}d
+.- r $Archive
+w $Archive
 EOF
 }
 
